language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - 8
  - 6

script:
  - npm run test

deploy:
  skip_cleanup: true
  provider: script
  script: npx semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
