language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 8
  - 6
jobs:
  include:
    - stage: test
      script:
        - npm run test
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
